name: Release OCPI.Net

on:
  repository_dispatch:
  push:
    tags:
    - "OCPI.Net-v[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  OCPI-Net:
    name: OCPI-Net
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/OCPI.Net-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build OCPI.Net.sln --configuration Release /p:Version=${VERSION}
          dotnet pack OCPI.Net.sln --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: |
          dotnet nuget push OCPI.Net.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push OCPI.Net.Contracts.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push OCPI.Net.Exceptions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push OCPI.Net.Controllers.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push OCPI.Net.Validation.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push OCPI.Net.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
